services:
  web:
    nixpack:
      buildCmd: "composer install"
      startCmd: "php artisan serve --host 0.0.0.0 --port $PORT"
      predeploy: "php artisan optimize && php artisan config:cache"
      postdeploy: "php artisan migrate --force"
    ports:
      - 8080
    environment:
      - ADAMSPAY_API_KEY=ap-6a40372d6f8b039f1108f5f6
      - ADAMSPAY_API_SECRET=a375afaaf41fe36c9f22a0042821d9a0
      - APP_DEBUG=false
      - APP_ENV=production
      - APP_KEY=base64:yx9D9R3vW7zIQQi4tgk5MYx++hM39mGC7ImS2yqeLQc=
      - APP_NAME=Laravel
      - APP_URL=http://localhost
      - AWS_ACCESS_KEY_ID=
      - AWS_BUCKET=
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY=
      - AWS_USE_PATH_STYLE_ENDPOINT=false
      - BROADCAST_DRIVER=pusher
      - CACHE_DRIVER=file
      - DB_CONNECTION=mysql
      - DB_DATABASE=railway
      - DB_HOST=containers-us-west-135.railway.app
      - DB_PASSWORD=5WnBugjGmI1gu7bfrY93
      - DB_PORT=7152
      - DB_USERNAME=root
      - FILESYSTEM_DISK=local
      - LOG_CHANNEL=stack
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=debug
      - MAIL_ENCRYPTION=null
      - MAIL_FROM_ADDRESS=hello@example.com
      - MAIL_FROM_NAME=${APP_NAME}
      - MAIL_HOST=mailpit
      - MAIL_MAILER=smtp
      - MAIL_PASSWORD=null
      - MAIL_PORT=1025
      - MAIL_USERNAME=null
      - MEMCACHED_HOST=127.0.0.1
      - NIXPACK_BUILD_CMD="composer install && php artisan optimize && php artisan config:cache && php artisan migrate --force"
      - PUSHER_APP_CLUSTER=us2
      - PUSHER_APP_ID=1573503
      - PUSHER_APP_KEY=874caa2abea82463850b
      - PUSHER_APP_SECRET=03e70fe543089b61f9e3
      - PUSHER_HOST=localhost
      - PUSHER_PORT=6001
      - PUSHER_SCHEME=http
      - QUEUE_CONNECTION=sync
      - REDIS_HOST=127.0.0.1
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=120
      - VITE_PUSHER_APP_CLUSTER=${PUSHER_APP_CLUSTER}
      - VITE_PUSHER_APP_KEY=${PUSHER_APP_KEY}
      - VITE_PUSHER_HOST=${PUSHER_HOST}
      - VITE_PUSHER_PORT=${PUSHER_PORT}
      - VITE_PUSHER_SCHEME=${PUSHER_SCHEME}
